# Generated by Django 5.0.2 on 2024-04-20 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facebook_app', '0003_posts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='post',
            field=models.CharField(max_length=1000),
        ),
    ]
