# Generated by Django 5.0.2 on 2024-04-24 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facebook_app', '0007_posts_date_added'),
    ]

    operations = [
        migrations.CreateModel(
            name='Photos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='photos/')),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Profile_Photos',
            fields=[
                ('image', models.ImageField(upload_to='photos/')),
                ('email', models.EmailField(max_length=254, primary_key=True, serialize=False)),
            ],
        ),
    ]
