# Generated by Django 5.0.2 on 2024-04-25 22:27

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facebook_app', '0008_photos_profile_photos'),
    ]

    operations = [
        migrations.AddField(
            model_name='photos',
            name='date_added',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='profile_photos',
            name='date_added',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
