# Generated by Django 5.0.2 on 2024-04-26 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facebook_app', '0009_photos_date_added_profile_photos_date_added'),
    ]

    operations = [
        migrations.CreateModel(
            name='Default_Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='photos/')),
            ],
        ),
    ]
